[package]
name = "reinda"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"


[dependencies]
ahash = "0.6"
reinda-core = { path = "reinda-core" }
reinda-macros = { path = "reinda-macros" }
base64 = "0.13"
bytes = "1"
sha2 = "0.9"
tokio = { version = "1", features = ["fs", "io-util"] }
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
