name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check-debug-dev:
    name: 'Build & test (debug, dev mode)'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        cargo test -p reinda-core
        cargo test -p reinda-macros
        cargo test


  check-debug-prod:
    name: 'Build & test (debug, prod mode -- `debug-is-prod`)'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features=debug-is-prod
    - name: Run tests
      run: |
        cargo test -p reinda-core --features=debug-is-prod
        cargo test -p reinda-macros --features=debug-is-prod
        cargo test --features=debug-is-prod


  check-release:
    name: 'Build & test (release, prod mode)'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: |
        cargo test -p reinda-core --release
        cargo test -p reinda-macros --release
        cargo test --release

  check-debug-prod-no-hash:
    name: 'Build & test (debug, prod mode, no hashing)'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --no-default-features --features=debug-is-prod
    - name: Run tests
      run: |
        cargo test -p reinda-core --no-default-features --features=debug-is-prod
        cargo test -p reinda-macros --no-default-features --features=debug-is-prod
        cargo test --no-default-features --features=debug-is-prod
