name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  main:
    strategy:
      matrix:
        mode:
          - ''
          - '--features=always-prod'
          - '--release'
        features:
          - '--no-default-features'
          - '--no-default-features --features=hash'
          - '--no-default-features --features=compress'
          - '--no-default-features --features=hash,compress'

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build ${{ matrix.mode }} ${{ matrix.features }}
    - name: Test
      run: cargo test ${{ matrix.mode }} ${{ matrix.features }}
